# Generated by Django 3.2.15 on 2022-09-14 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImgurModel',
            fields=[
                ('ImageId', models.AutoField(primary_key=True, serialize=False)),
                ('ImageName', models.CharField(default='Untitled', max_length=100)),
                ('ImageDescription', models.CharField(max_length=100, null=True)),
                ('ImageURL', models.CharField(max_length=500)),
                ('ImageFav', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('UserId', models.AutoField(primary_key=True, serialize=False)),
                ('Username', models.CharField(max_length=100)),
                ('UserUsername', models.CharField(max_length=100)),
                ('UserPassword', models.CharField(max_length=100)),
                ('ClientID', models.CharField(max_length=100)),
                ('ClientSecret', models.CharField(max_length=100)),
                ('RefreshToken', models.CharField(max_length=100)),
                ('DateOfJoining', models.DateField(null=True)),
            ],
        ),
    ]
