# Generated by Django 3.2.15 on 2022-09-13 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImgurModel',
            fields=[
                ('ImageId', models.AutoField(primary_key=True, serialize=False)),
                ('ImageName', models.CharField(max_length=100)),
                ('ImageDescription', models.CharField(max_length=100)),
                ('ImageURL', models.CharField(max_length=500)),
                ('ImageFav', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserUsername', models.CharField(max_length=100)),
                ('UserPassword', models.CharField(max_length=100)),
            ],
        ),
    ]
