# Generated by Django 3.2.15 on 2022-09-14 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Username',
            field=models.CharField(default='Tom', max_length=100),
            preserve_default=False,
        ),
    ]
