# Generated by Django 3.2.15 on 2022-09-14 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0003_user_dateofjoining'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ClientID',
            field=models.CharField(default='8483aace5b29319', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='ClientSecret',
            field=models.CharField(default='4ec186fc50ddc75b69dd5b5bacefc9af92733194', max_length=100),
            preserve_default=False,
        ),
    ]
