# Generated by Django 3.2.15 on 2022-09-14 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0004_auto_20220914_0802'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='RefreshToken',
            field=models.CharField(default='462a87874858dd27b90de367db590cfce0c20413', max_length=100),
            preserve_default=False,
        ),
    ]
