# Generated by Django 3.2.15 on 2022-09-14 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0004_auto_20220914_0802'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='RefreshToken',
            field=models.CharField(default='8943e89e7c203b0f260ea9aba8ced7c24962ab75', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='imgurmodel',
            name='ImageDescription',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='imgurmodel',
            name='ImageName',
            field=models.CharField(default='Untitled', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='DateOfJoining',
            field=models.DateField(null=True),
        ),
    ]
